# Generated by Django 4.2.1 on 2023-06-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.URLField(blank=True),
        ),
    ]
