# Generated by Django 4.2.1 on 2023-05-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_room_name_alter_amenity_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.AddField(
            model_name="room",
            name="toilet",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
