# Generated by Django 4.2.1 on 2023-05-27 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="ChattingRoom",
            new_name="room",
        ),
    ]
